### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by DonaldTsang** [sakharovaan/hydrus-unleashed#10]
Just wondering if you have any IRC/Discord/Matrix.

**Comment by sakharovaan** [comment]
well, from all mentioned messengers I have only discord, _Aeterna Historia#6865_

**Comment by DonaldTsang** [comment]
Thanks, @sakharovaan could you add that to the ReadMe? Also do you have a Discord server for this?
Love ya work.

**Comment by sakharovaan** [comment]
Added contact info for main ways of communication to github profile
